# Generated by Django 4.2.11 on 2026-04-24 08:43

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('parent_name', models.CharField(blank=True, max_length=140)),
                ('contact_number', models.CharField(blank=True, max_length=24)),
                ('address', models.TextField(blank=True)),
                ('standard', models.CharField(blank=True, max_length=64)),
                ('batch_time', models.CharField(blank=True, max_length=64)),
                ('roll_number', models.CharField(blank=True, max_length=32)),
                ('admission_date', models.DateField(blank=True, null=True)),
                ('decided_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('paid_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=16)),
                ('critical_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='branches.branch')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['-created_at'],
            },
        ),
    ]
