# Generated by Django 4.2.11 on 2026-05-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='target_role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('assistant', 'Assistant'), ('all', 'All Users')], default='all', max_length=24),
        ),
    ]
